version: '2'
services:
  tdiary_puma:
    image: tdiary_puma:latest
    build:
      context: ./tdiary_puma
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
    env_file: .env
    command: /tdiary/tdiary-core/entrypoint.sh
    volumes:
      - ./volumes/tdiary/tdiary-core/data:/tdiary/tdiary-core/data:rw
      - ./volumes/tdiary/tdiary-core/public:/tdiary/tdiary-core/public:rw

  nginx_puma:
    image: nginx_puma:latest
    build:
      context: ./nginx_puma
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        SERVER_NAME: ${SERVER_NAME}
        TDIARY_BASE_DIR: ${TDIARY_BASE_DIR}
    command: /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    ports:
      - "80:80"
    volumes:
      - ./volumes/var/log/nginx:/var/log/nginx:rw
    volumes_from:
      - tdiary_puma
    depends_on:
      - tdiary_puma

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - nginx_puma
    volumes:
      - ./volumes/var/lib/https-portal:/var/lib/https-portal
    restart: always
    environment:
      DOMAINS: "${SERVER_NAME} => https://${HTTPS_PORTAL_DOMAIN_NAME}"
